### ISSUE TITLE
Proposal to Curb Use of Acronyms

### ISSUE THREAD

**Issue by kayaelle** [w3c-ccg/CCG101#2]
I would like to suggest that we stop using acronyms in the documentation and when discussing technologies and standards in this effort. Or conversely, we consistently spell out the terms with the acronym in parentheses to help others understand the vernacular. 

So for instance: 
self-sovereign identity (SSI) vs SSI
decentralized identifier (DID) vs DID

The reasoning is that acronyms make it more challenging to understand new concepts. Using real terms also reinforces understanding. 

Is this the correct location for this suggestion? Do we have a guide?

**Comment by vsnt** [comment]
I really like this suggestion, however I think it *could* be hard to enforce. That doesn't mean I don't think we shouldn't try - we should. And it would be great to have a list of normally used ones. I actually put a slide explaining acronyms in my TPAC deck. I'll post those here as a start.

**Comment by vsnt** [comment]
Here are the ones I included in my TPAC presentation. They are a start and we can build upon them. 

W3C = World Wide Web Consortium
VC = Verifiable Credential
DID = Decentralized Identifier
CCG = Credentials Community Group
IPR = Intellectual Property Rights
SVIP = Silicon Valley Innovation Program (at DHS)
DHS = Department of Homeland Security
DIF = Decentralized Identity Foundation
DIACC = Digital Identity & Authentication Council of Canada
ToIP = Trust over IP (Linux Foundation Group)
APAC = Asia Pacific

**Comment by tkendal** [comment]
@kayaelle Great suggestion! @vsnt, perhaps within the context of **all 101 material** as opposed to ccg-wide, which as you say, would be a big challenge to enforce.

**Comment by kayaelle** [comment]
Agreed @tkendal! Within the 101 material is a great start and was the intention in my original submission.  I should have made that clearer. We can highlight @vsnt's key and discourage the use of acronyms as much as possible.

Thanks!

**Comment by vsnt** [comment]
I think we are all in agreement here and we have started an acronyms file here:https://github.com/w3c-ccg/CCG101/blob/main/Acronyms.md 

Closing this issue because we have resolved it. Thanks all.
