### ISSUE TITLE
Recording of Manu's overview of CCG-centered spec and standards work

### ISSUE THREAD

**Issue by bumblefudge** [w3c-ccg/CCG101#3]
from Wednesday 2March 2021

[recording](https://us02web.zoom.us/rec/share/WOKrQyAymxpWRVKXkw3bEJQVDYApFikAdaBIPnlTT4GBEgEnXELGPZG1rRGO2fp4.QgPtTRgAc9g7BbEW?startTime=1614779841000)
and
[minutes](https://github.com/decentralized-identity/interoperability/blob/master/agenda.md#agenda---3-mar-2021---useu-time-0600pt---manu-sporny-digital-bazaar-report-out-on-specifications-incubated-in-w3c-ccg)

**Comment by bumblefudge** [comment]
also happy to post to the DIF youtube channel, or move it to w3c-controlled storage!

**Comment by vsnt** [comment]
Do you want to move these to here @bumblefudge ? https://drive.google.com/drive/u/0/folders/1MDQi2095AFdwKGCKV8sDnsInGb97Mbd6

**Comment by bumblefudge** [comment]
oh, sorry, just seeing this.  I don't have local copies of things on youtube, and i'm on a computer while traveling that it would take hours to download/upload on.  also note that all DIF recordings are here:
https://docs.google.com/spreadsheets/d/1wgccmMvIImx30qVE9GhRKWWv3vmL2ZyUauuKx3IfRmA/edit#gid=2146749098
DIF interop archive here:
https://github.com/decentralized-identity/interoperability/blob/master/agenda.md
DIF biweekly archive here (high-level overviews of all other DIF groups):
https://github.com/decentralized-identity/org/blob/master/bi-weekly/agenda.md
and all youtube links to the subset of those that get uploaded for public consumption are here:
https://studio.youtube.com/channel/UCicZIzvOXOyij0A6jlA7nxQ/playlists?c=UCicZIzvOXOyij0A6jlA7nxQ

**Comment by vsnt** [comment]
OK. I'll close this item for now then.
